-- MySQL Script generated by MySQL Workbench
-- Qua 28 Set 2016 17:37:46 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema witc
-- -----------------------------------------------------

USE `witc` ;

-- -----------------------------------------------------
-- Table `witc`.`ConvidadoPerfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `witc`.`ConvidadoPerfil` (
  `idPerfil` INT UNSIGNED NOT NULL COMMENT '',
  `idPerfilConvidado` INT UNSIGNED NOT NULL COMMENT '',
  `idLivro` INT UNSIGNED NOT NULL COMMENT '',
  `dataSolicitacao` DATE NOT NULL COMMENT '',
  UNIQUE INDEX `idPerfil_UNIQUE` (`idPerfil` ASC)  COMMENT '',
  UNIQUE INDEX `idPerfilConvidado_UNIQUE` (`idPerfilConvidado` ASC)  COMMENT '',
  UNIQUE INDEX `idLivro_UNIQUE` (`idLivro` ASC)  COMMENT '',
  CONSTRAINT `fk_ConvidadoPerfil_1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `witc`.`Perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvidadoPerfil_2`
    FOREIGN KEY (`idPerfilConvidado`)
    REFERENCES `witc`.`Perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvidadoPerfil_3`
    FOREIGN KEY (`idLivro`)
    REFERENCES `witc`.`Livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
