-- MySQL Script generated by MySQL Workbench
-- Qua 28 Set 2016 17:37:46 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema witc
-- -----------------------------------------------------

USE `witc` ;

-- -----------------------------------------------------
-- Table `witc`.`ConvidadoPerfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `witc`.`ConvidadoPerfil` (
  `idPerfil` INT UNSIGNED NOT NULL,
  `idPerfilConvidado` INT UNSIGNED NOT NULL,
  `idLivro` INT UNSIGNED NOT NULL,
  `dataSolicitacao` DATE NOT NULL,
  PRIMARY KEY (`idPerfilConvidado`, `idPerfil`, `idLivro`),
  CONSTRAINT `fk_ConvidadoPerfil_1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `witc`.`Perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvidadoPerfil_2`
    FOREIGN KEY (`idPerfilConvidado`)
    REFERENCES `witc`.`Perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvidadoPerfil_3`
    FOREIGN KEY (`idLivro`)
    REFERENCES `witc`.`Livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Procedure `proc_edicao` realizar a pesquisa de amigos para sugerir
-- -----------------------------------------------------
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `proc_edicao`(IN usuario INT)
BEGIN
START TRANSACTION;
(SELECT * FROM witc.Perfil WHERE idUsuario IN 
(SELECT id FROM witc.Usuario WHERE id IN 
(SELECT a.idUsuario FROM witc.Usuario_tem_Amigo a WHERE a.idAmigo = usuario AND a.dataAceitacao IS NOT NULL AND a.amigoStatus = TRUE) OR id IN 
(SELECT b.idAmigo FROM witc.Usuario_tem_Amigo b WHERE b.idUsuario = usuario AND b.dataAceitacao IS NOT NULL AND b.amigoStatus = TRUE)));
COMMIT;
END$$
DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
