-- MySQL Script generated by MySQL Workbench
-- Qua 28 Set 2016 17:37:46 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema witc
-- -----------------------------------------------------

USE `witc` ;

ALTER TABLE `witc`.`usuario` 
ADD COLUMN `fotoCapa` LONGBLOB NULL DEFAULT NULL AFTER `foto`;

-- -----------------------------------------------------
-- Table `witc`.`timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `witc`.`timeline` (
  `timeline` INT UNSIGNED AUTO INCREMENT NOT NULL,
  `idUsuario` INT(10) UNSIGNED NOT NULL,
  `idAmigo` INT(10) UNSIGNED NOT NULL,
  `dataPublicacao` DATETIME NOT NULL,
  `publicacao` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`idTimeline`),
  INDEX `fk_timeline_usuario_idx` (`idUsuario` ASC),
  INDEX `fk_timeline_usuario1_idx` (`idAmigo` ASC),
  CONSTRAINT `fk_timeline_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `witc`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timeline_usuario1`
    FOREIGN KEY (`idAmigo`)
    REFERENCES `witc`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `witc`.`timeline` 
CHANGE COLUMN `idTimeline` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ;
