-- MySQL Script generated by MySQL Workbench
-- Qua 28 Set 2016 17:37:46 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema witc
-- -----------------------------------------------------

USE `witc` ;

ALTER TABLE `witc`.`Usuario` 
ADD COLUMN `status` ENUM('Pensando', 'Editando', 'Revisando', 'Lendo') NOT NULL 
DEFAULT 'Pensando' AFTER `senha`;